trigger:
  branches:
      include:
      - master
      - refs/tags/*
pr:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  BuildConfiguration: 'Release'

steps:
# .NET Core SDK/Runtime Installer
# Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
#- task: DotNetCoreInstaller@0
#  inputs:
#    packageType: 'sdk' # Options: runtime, sdk
#    version: '2.2.105' 
#
#- task: DotNetCoreCLI@2
#  displayName: Restore
#  inputs:
#    command: restore
#    projects: '**/*.csproj'
#
- script: dotnet --version
  displayName: Show dotnet version

- task: DotNetCoreCLI@2
  displayName: Build package projects
  inputs:
    projects: |
     '**/*.csproj'
     !**/*Tests.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: Build test projects
  inputs:
    projects: |
     'src/test/**/*.csproj
    arguments: '--configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/test/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build --no-restore'

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Package'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Package/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'ab2dfb26-dc54-4f3e-b3c8-cce82f141406'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Package'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
